### ISSUE TITLE
Error: image ibmnode:v1.1 not found

### ISSUE THREAD

**Issue by iainhouston** [osipov/district-insurance-sample#2]
```
   ...
   No user-defined env variables have been set

Running Environment Variable Groups:
BLUEMIX_REGION: ibm:yp:eu-gb

Staging Environment Variable Groups:
BLUEMIX_REGION: ibm:yp:eu-gb

Note the Tradeoff Analytics password and username above and copy/paste them when prompted
Press any key to continue.
make[1]: Leaving directory '/home/docker/district-insurance-sample'
make[1]: Entering directory '/home/docker/district-insurance-sample'
cp scripts/build/Dockerfile .
cp scripts/build/.dockerignore .
docker build -t district-insurance-sample .
Sending build context to Docker daemon 6.987 MB
Step 1 : FROM registry.ng.bluemix.net/ibmnode:v1.1
Pulling repository registry.ng.bluemix.net/ibmnode
Error: image ibmnode:v1.1 not found
scripts/build/Makefile:9: recipe for target 'build-local' failed
make[1]: *** [build-local] Error 1
make[1]: Leaving directory '/home/docker/district-insurance-sample'
Makefile:15: recipe for target 'build-release-local' failed
make: *** [build-release-local] Error 2
```

**Comment by osipov** [comment]
Hi @iainhouston  -- please confirm that you've executed the following commands from the updated README.md instructions prior to running `make build-release-local`

```
cf install-plugin https://static-ice.ng.bluemix.net/ibm-containers-linux_x64
cf ic init
```

**Comment by iainhouston** [comment]
Thanks @osipov . I started afresh on a newly-created docker machine and followed all the steps including installing the Cloud Foundry plugin in the latest README. 

Still the same error as above at the same point.

The `cf ic init` step originally combined the `cf login` step if I recall. But on both this and immediately previous attempts `cf ic init` has prompted `cf login` and then, during the `make  build-release-local` step we are asked to provide Cloud Foundry credentials again.

**Comment by iainhouston** [comment]
BTW can also confirm that _"existing instances of the container and tradeoff analytics services in the organisation"_ **were** deleted before re-trying.

**Comment by osipov** [comment]
@iainhouston ok, so i simplified the process a bit, and the `make build-release-local` works correctly in the step you've described, i.e. building from ibmnode:v1.1 image. If you are still having trouble with this image, I suggest trying to use the US South region API endpoint vs. UK endpoint. The difference is described here: http://stackoverflow.com/questions/30068471/what-is-the-difference-between-api-mybluemix-vs-api-ng-bluemix/30073346#30073346
